home/urls.py
from turtle import home
from unicodedata import name
from django.urls import path 
from . import views 
app_name='home'

urlpatterns = [
    path('',views.index,name='index'),
    path('room/<str:pk>',views.room,name='room'),
    path('create_room/',views.createRoom,name='create_room'),
    path('update_room/<str:pk>',views.updateRoom,name='update_room'),
    path('delete/<str:pk>',views.delelteRoom,name='delete_room'),
    path("registerForm/",views.registerUser, name="register_user"),
    path("loginForm/",views.Login, name="login_form"),
    path("logout/",views.Logout,name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('view/',include('home.urls'))
 
   
]

home/models.py
import email
from pyexpat import model
from tkinter import CASCADE
from turtle import update
from unicodedata import name
from venv import create
from django.db import models
from django.contrib.auth.models import User
from numpy import str_

# Create your models here.
class Topic(models.Model):
    name=models.CharField(max_length=50)
 
    def __str__(self):
         return self.name
        


class Room(models.Model):
    host=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    topic=models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True )
    name=models.CharField(max_length=50)
    description=models.TextField(null=True,blank=True)
    update=models.DateTimeField(auto_now=True)
    #participants=
    created=models.DateTimeField(auto_now_add=True) 
    
    class Meta:
        ordering = ['-update' , '-created']
        
    def __str__(self):
        return self.name
    

class Message(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    body = models.TextField()
    update=models.DateTimeField(auto_now=True)
    create=models.DateTimeField(auto_now_add=True)
    
    def __str__(self) :
        return self.body[0:50]
    
    

home/forms.py
import email
from pyexpat import model
import django
from django.forms import ModelForm, PasswordInput
from .models import Room
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class RoomForm(ModelForm):
    class Meta:
        model=Room
        fields = '__all__' 
        
class CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']
    

home/views.py
from curses import REPORT_MOUSE_POSITION
from multiprocessing import context
from pydoc_data.topics import topics
from re import I
from unicodedata import name
from urllib import request
from urllib.request import Request
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render,HttpResponseRedirect
from .models import Room, Topic
from .forms import RoomForm,CreateUserForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here. 
# rooms=[
#     {'id':1,'name':'HoangDepTrai' },
#     {'id':2,'name':'HoangVipPro' },
#     {'id':3,'name':'HoangNe' }   
# ]

def index(request):
    q=request.GET.get('q') if request.GET.get('q') != None  else ''  

    rooms=Room.objects.filter(Q(topic__name__icontains=q)|
                              Q(name__icontains=q)|
                              Q(description__icontains=q)
                              )
    
    topics=Topic.objects.all()
    
    context={'rooms':rooms,'topics':topics}
    return render(request,'pages/index.html',context)


def room(request,pk):
    room=Room.objects.get(id=pk)
    context={'room':room}
    return render(request,'pages/room.html',context)

@login_required(login_url='home:login_form')   
def createRoom(request):
    form=RoomForm()
    if request.method == 'POST':
          form = RoomForm(request.POST)
          if form.is_valid() :
              form.save()
              return redirect('home:index')
    context={'form':form}
    return render(request,'pages/room_form.html',context)
 
@login_required(login_url='home:login_form')      
def updateRoom(request,pk):
    room=Room.objects.get(id=pk)
    form=RoomForm(instance=room)
    
    if request.user != room.host:
        return HttpResponse('ban khong co quyen tury cap ')
    
    if request.method=='POST':
        form=RoomForm(request.POST,instance=room)
        if form.is_valid():
            form.save()
            return redirect('home:index')
    context={'form':form}
    return render(request,'pages/room_form.html',context)

def delelteRoom(request,pk):
    room=Room.objects.get(id=pk) 
    if request.method=='POST':
        room.delete()
        return redirect('home:index')
    return render(request,'pages/delete.html',{'obj':room})

def registerUser(request):  
    page='register'
    form=CreateUserForm()
    if request.method=='POST':
        form=CreateUserForm(request.POST)
        if form.is_valid():
             form.save()
             user=form.cleaned_data.get('username')
             messages.success(request,'Tao Thanh Cong'+user)
        else:
            messages.error(request,'Co loi')
    context={'form':form,'page':page}
    return render(request,'pages/login-register-form.html',context)      

def Login(request):
    page='login'
    if request.user.is_authenticated:
        return redirect('home:index')
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        try:
            user=User.objects.get(username=username)
        except:
            messages.error(request,'tai khoan khong ton tai ')  
        user=authenticate(request , username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home:index')
        else:
            messages.error(request,'sai tai khoan hoac mat khau ')
    context={'page':page}
    return render(request,'pages/login-register-form.html',context)

def Logout(request):
    logout(request)
    return redirect('home:index')
    

      

home/templates/pages/delete.html
{% extends 'pages/page.html' %}
{% block content %}
   <form action="" method="POST">

    {% csrf_token %} 
    <p>Ban muon xoa chu "{{obj}}" ?</p>
    <a href="{{ request.META.HTTP_REFERER }}"> Tro Lai   </a>
    <input type="submit" value='confirm'>

   </form>
 
    
{% endblock content %}

home/templates/pages/index.html
{% extends 'pages/page.html' %}
{% block content %} 
<div>
     <div class="container-fluid">


      <nav class="navbar navbar-expand-sm justify-content-center">
         <ul class="navbar-nav">
            <li class="nav-item">
               <a class="nav-link" href="{% url 'home:create_room' %}">Create Room</a>               
            </li> 
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:register_user' %}">Creat user</a>
            </li>
           
           {% if  request.user.is_authenticated %}
             <div>{{ user.username }}  </div>
             <li class="nav-item">       
               <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
             </li>
             {% else %}
             <li class="nav-item">
               <a class="nav-link" href="{% url 'home:login_form' %}">Login</a>
            </li>
           {% endif %}   
         </ul>
    </nav>

        <div class="row">

             <form action="{% url 'home:index' %}" method="GET"> 
                <input type="text" placeholder='tim kiem' name='q'>
             </form>

             <div class="col-4">
                   Browser
                   <br>
                   <a href="{% url 'home:index' %}">All</a>
                  {% for topic in topics %}
                  <br>
                 <a href="{% url 'home:index' %}?q={{topic.name}}">{{topic}}</a>
      
                  {% endfor %}
             </div>
          
              <div class="col-8">
               {% for room in rooms   %}
                   
                  {% if request.user == room.host %}
                       <span>{{room.id}}</span>
                       <br>
                       <a href="{% url 'home:update_room' room.id %}"> Edit</a>
                       <br>
                       <a href="{% url 'home:delete_room' room.id %}">delete</a>   
                       <br>
                   {% endif %}  
                      <span>@{{room.host.username}}</span>
                      <div><a href="{% url 'home:room' room.id  %}">{{room.name}} </a></div>
                       <small>{{room.topic.name}}</small>
                       <br>                                      
                     <br>
                     <br>
                 {% endfor %}
                      
                    <br>                      
             </div>

        </div>
       

     </div>
</div>


  
{% endblock content %}

home/templates/pages/login-register-form.html
{% extends 'pages/page.html' %}
{% block content %}
  
  {% if page == 'login' %}
  
  <div>
      <form action="" method="post">
         {% csrf_token %}
          <label for="">Username</label>
          <input type="text"  placeholder="enterusername" name="username">
 
          <label for="">Password</label>
          <input type="password"  name="password">

        <input type="submit" value="dang nhap">
      </form> 
      <label for="">Ban chua co tai khoan</label>
      <a href="{% url 'home:register_user' %}">Dang ky</a>
  </div>  

  
         {% if messages %}
          <ul class="messages">
               {% for message in messages  %}
                   <li>{{message}}</li>
               {% endfor %}
          </ul>
       
         {% endif %}

      {% else %}      
  <form action="" method="POST">
    {% csrf_token %}
      Ten Dang Nhap 
      {{form.username}}
      <br>
      Mat Khau
      {{form.password1}}
      <br>
      Nhap lai mat Khau
      {{form.password2}}
      <br>
      Mhap email
      {{form.email}}
      <br>
    <input type="submit" value="submit">

    </form>
    {{form.errors}}

    <label for="">Ban da co tai khoan</label>
    <a href="{% url 'home:login_form' %}">Dang nhap</a>
    {% endif %}

{% endblock content %}

home/templates/pages/page.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Document</title>
</head>  
<body>   
  
    {% block content %}{% endblock content %}
    
    
</body>
</html>

home/templates/pages/room.html
{% extends 'pages/page.html' %}
{% block content %}
   <div>{{room.name}}  </div> 
   <div>{{room.description}}  </div> 
{% endblock content %}

home/templates/pages/room_form.html
{% extends 'pages/page.html' %}

{% block content %}
  <div>
    <form action="" method="POST">
    {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
  </div>
{% endblock content %}